# Generated by Django 4.2.6 on 2023-11-07 08:36

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_profile_profile_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasport',
            new_name='Passport',
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name': 'passport', 'verbose_name_plural': 'passports'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pasport',
        ),
        migrations.AddField(
            model_name='profile',
            name='passport',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.passport'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_sertificate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.birthsertificate'),
        ),
    ]
