# Generated by Django 4.2.6 on 2023-11-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_pasport_passport_alter_passport_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Image',
            new_name='image',
        ),
    ]
