# Generated by Django 4.2.8 on 2023-12-16 10:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_image.jpg",
                null=True,
                upload_to=users.models.user_directory_path,
            ),
        ),
    ]
