# Generated by Django 4.2.8 on 2023-12-16 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_sertificate",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.birthsertificate",
            ),
        ),
    ]
