# Generated by Django 4.2.6 on 2023-11-09 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('patronymic', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'abstract profile',
                'verbose_name_plural': 'abstract profiles',
            },
        ),
        migrations.CreateModel(
            name='RelativeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'relative status',
                'verbose_name_plural': 'relative statuses',
            },
        ),
        migrations.CreateModel(
            name='Relatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.abstractprofile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.relativestatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'relative',
                'verbose_name_plural': 'relitives',
            },
        ),
    ]
