# Generated by Django 4.2.8 on 2023-12-12 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_rename_adress_profile_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wedding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wedding",
            name="change_last_name",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="wedding",
            name="event_datatime",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wedding",
            name="profile_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wedding",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="wedding.weddingstatus",
            ),
        ),
        migrations.AddField(
            model_name="wedding",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
