# Generated by Django 4.2.8 on 2023-12-12 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wedding", "0002_wedding_change_last_name_wedding_event_datatime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wedding",
            old_name="profile_id",
            new_name="profile",
        ),
        migrations.RenameField(
            model_name="wedding",
            old_name="user_id",
            new_name="user",
        ),
    ]
