# Generated by Django 4.2.8 on 2023-12-12 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wedding", "0003_rename_profile_id_wedding_profile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wedding",
            old_name="event_datatime",
            new_name="event_datetime",
        ),
    ]
