# Generated by Django 4.2.8 on 2023-12-17 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("relationships", "0001_initial"),
        ("wedding", "0005_alter_wedding_options_alter_wedding_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="witnesses",
            name="wedding",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="wedding.wedding",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="witnesses",
            name="witness",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="relationships.abstractprofile",
            ),
            preserve_default=False,
        ),
    ]
