# Generated by Django 4.2.8 on 2023-12-17 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wedding", "0006_witnesses_wedding_witnesses_witness"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="witnesses",
            options={"verbose_name": "witness", "verbose_name_plural": "witnesses"},
        ),
    ]
