# Generated by Django 4.2.8 on 2023-12-20 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("relationships", "0002_alter_relatives_unique_together"),
        ("wedding", "0007_alter_witnesses_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="witnesses",
            unique_together={("wedding", "witness")},
        ),
    ]
