# Generated by Django 4.2.8 on 2023-12-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wedding", "0008_alter_witnesses_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthSertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_place", models.CharField(max_length=100)),
                ("place_of_birth", models.CharField(max_length=100)),
                ("vital_record", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "birth sertificate",
                "verbose_name_plural": "birth sertificates",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("patronymic", models.CharField(max_length=50, null=True)),
                ("birth_date", models.DateField()),
            ],
            options={
                "verbose_name": "Child",
                "verbose_name_plural": "Children",
                "unique_together": {
                    ("last_name", "first_name", "patronymic", "birth_date")
                },
            },
        ),
        migrations.CreateModel(
            name="ChildStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "child status",
                "verbose_name_plural": "child statuses",
            },
        ),
        migrations.CreateModel(
            name="Children",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birth_sertificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wedding.birthsertificate",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wedding.child"
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wedding.childstatus",
                    ),
                ),
                (
                    "wedding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wedding.wedding",
                    ),
                ),
            ],
            options={
                "verbose_name": "children",
                "unique_together": {
                    ("child", "wedding", "birth_sertificate", "status")
                },
            },
        ),
    ]
