# Generated by Django 4.2.8 on 2023-12-20 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wedding", "0011_child_sex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="birthsertificate",
            name="registration_place",
        ),
    ]
